labels:
  type: exec

pipeline:
- name: test
  image: bash
  commands:
  - nix run 'nixpkgs#hello'

- name: notify
  image: bash
  secrets:
  - source: matrix_homeserver
    target: address
  - source: matrix_roomid
    target: room
  - source: matrix_username
    target: user
  - source: matrix_password
    target: pass
  commands:
  - nix run 'github:ambroisie/matrix-notifier'
  when:
    status:
    - failure
    - success
